config/routes.rb
Rails.application.routes.draw do
  # articles: controller index page
  root "articles#index"
  
  get "/articles", to: "articles#index"
  get "/khachsan", to: "articles#khachsan"
  get "/detail", to: "articles#detail"
  get "/tintuc", to: "articles#tintuc"
  get "/tintuc_chitiet", to: "articles#tintuc_chitiet"
  get "/gioithieu", to: "articles#gioithieu"
  get "/lienhe", to: "articles#lienhe"
  get "search", to: "articles#search"
  get "post_search", to: "articles#post_search"
  post "new_order", to: "order#create"
  get "list_order", to: "articles#list_order"

  resources :comments

  # users, session: controller login, register and logout
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  get  "logout"   => "session#destroy"
  get "register"    => "users#new"
  resources :users

  # admin space
  get "admin", to: "admin_session#new"
  post "admin_login", to: "admin_session#login"
  get "admin_logout", to: "admin_session#destroy"
  get "dashboard", to: "admin#index"

  scope 'admin' do
      get 'category', to: 'category#category'
      get 'new_category', to: 'category#new'
      post 'create_category', to: 'category#create'
      get 'delete_category', to: 'category#destroy'
      get 'edit_category', to: 'category#edit'
      post 'update_category', to: 'category#update'

      get 'product', to: 'product#product'
      get 'new_product', to: 'product#new'
      post 'create_product', to: 'product#create'
      get 'delete_product', to: 'product#destroy'
      get 'edit_product', to: 'product#edit'
      post 'update_product', to: 'product#update'

      get 'gallery', to: 'gallery#show'
      get 'new_gallery', to: 'gallery#new'
      post 'create_gallery', to: 'gallery#create'

      get 'post', to: 'post#post'
      get 'new_post', to: 'post#new'
      post 'create_post', to: 'post#create'
      get 'edit_post', to: 'post#edit'
      post 'update_post', to: 'post#update'
      get 'delete_post', to: 'post#destroy'

      get 'all_comments', to: 'comments#index'
      get 'delete_comment', to: 'comments#destroy'

      get 'all_order', to: 'order#index'
      get 'order_confirm', to: 'order#confirm'
      get 'order_cancel', to: 'order#cancel'

      get 'account', to: 'admin#account'
      get 'change_pass' , to: "admin#change_pass"
      post 'update_account', to: "admin#update"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "articles_layout"
  after_action :get_url_back_login

  def index
    @sanpham = Hotel.all.order("id DESC").limit(10)
    @all_post = Post.all.order("id DESC").limit(3)
  end
  def khachsan
    @all_category = CategoryHotel.all
    if params[:show]
      session["show"] = params[:show]
    end

    if session["show"]
      @show = session["show"] 
    else  
      @show = 4
    end 

    if params[:id]
      @pagy, @all_product = pagy(CategoryHotel.find(params[:id]).hotel.where("status = 0").order("id DESC"), items: @show)
    else 
      if params[:filter]
        if  params[:filter]=="1"
          @pagy, @all_product = pagy(Hotel.where("price_discount <= ?", 1000000).where("status = 0").order("id DESC"), items: @show)
        elsif params[:filter]=="2"
          @pagy, @all_product = pagy(Hotel.where("price_discount  BETWEEN ? AND ?", 1000000,5000000).where("status = 0").order("id DESC"), items: @show)
        elsif params[:filter]=="3"
          @pagy, @all_product = pagy(Hotel.where("price_discount  BETWEEN ? AND ?", 5000000,10000000).where("status = 0").order("id DESC"), items: @show)
        elsif params[:filter]=="4"
          @pagy, @all_product = pagy(Hotel.where("price_discount >= ?", 10000000).where("status = 0").order("id DESC"), items: @show)
        elsif params[:filter]=="5"
          @pagy, @all_product = pagy(Hotel.order("price_discount ASC"), items: @show)
        elsif params[:filter]=="6"
          @pagy, @all_product = pagy(Hotel.order("price_discount DESC"), items: @show)
        else  
          @pagy, @all_product = pagy(Hotel.all.where("status = 0").order("id DESC"), items: @show)
        end
      else  
        @pagy, @all_product = pagy(Hotel.all.where("status = 0").order("id DESC"), items: @show)
      end
    end
    
    
  end

  def detail
    @product = Hotel.find(params[:id])
    @comments = Comment.where(["hotel_id = :u", { u: params[:id] }])
    if @product.view!=nil
      @product.view +=1
    else 
      @product.view = 1
    end
    @product.save
  end

  def tintuc
    @pagy, @all_post = pagy(Post.all.order("id DESC"), items: 3)
    @all_post_latest = Post.all.order("id DESC").limit(5)
  end

  def tintuc_chitiet
    @post = Post.find(params[:id])
    if @post.post_view 
      @post.post_view +=1
    else  
      @post.post_view =1
    end
    @post.save
    @all_post = Post.all.order("id DESC").limit(5)
  end 

  def gioithieu
  end
  
  def lienhe
  end

  def list_order
    @all_order = Order.where(["user_id = :u", { u: session[:customer_id] }]).order("id DESC")
  end

  def search 
    @all_category = CategoryHotel.all
    @pagy, @all_product = pagy(Hotel.where("name LIKE ?","%"+params[:text]+"%").where("status = 0").order("id DESC"), items: 4)
    render "khachsan"
  end

  def post_search
    @pagy, @all_post = pagy(Post.where("post_title LIKE ?","%"+params[:text]+"%").order("id DESC"), items: 3)
    @all_post_latest = Post.all.order("id DESC").limit(5)
    render "tintuc"
  end

  def get_url_back_login  
    session.delete(:login_back_url)
    session[:login_back_url] = request.referrer
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/list_order.html.erb
<div class="wrapper">

    <div class="main_gt">
        <header>
            <nav class="nav_Bar container navbar navbar-expand-lg navbar-primary|secondary|success|danger|warning|info|light|dark bg-primary|secondary|success|danger|warning|info|light|dark">
                <a class="navbar-brand logo_tieude" href="<%= root_path %>">LangCoBeach</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="fas fa-bars icon_bar"></i>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<%= root_path %>">TRANG CHỦ <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= khachsan_path %>">KHÁCH SẠN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= tintuc_path %>">TIN TỨC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= gioithieu_path %>">GIỚI THIỆU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= lienhe_path %>">LIÊN HỆ</a>
                        </li>
                        <li class="nav-item search_nav_cha">
                            <div class="search">
                                <div class="nav-link">
                                    <span>Tìm kiếm</span>
                                    <i class="fa fa-search"></i>
                                </div>
                            </div>
                            <div class="form_search_navbar flex-row">
                                <%= form_tag(search_path, method: :get) do   %>
                                <%= text_field_tag :text,"", class:'form-control', required: 'true' %>
                                <div class="icon_search_navbar">
                                    <button type="submit" class="form-control"><i class="fa fa-search"></i></button>
                                </div>
                                <% end %>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a href="<%= list_order_path %>">
                                <div class="giohang">
                                    <div class="nav-link">
                                        <span>Đơn hàng</span>
                                        <i class="fa fa-shopping-bag"></i>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <% if session[:username] %>
                            <%= link_to 'logout', :action => 'go' do %>
                            <div class="giohang dangnhap">
                                <div class="nav-link">
                                    <span id="username"> <%= session[:username] %></span>
                                    <i class="fas fa-sign-out-alt"></i>
                                </div>
                            </div>
                            <% end %>
                            <% else %>
                            <%= link_to 'login', :action => 'go' do %>
                            <div class="giohang dangnhap">
                                <div class="nav-link">
                                    <span id="username"> Đăng nhập</span>
                                    <i class="fas fa-sign-in-alt"></i>
                                </div>
                            </div>
                            <% end %>
                            <% end %>
                        </li>
                    </ul>

                </div>
            </nav>
        </header>
        <div class="demogh">
            <div class="tieude container">
                <h3>Đơn hàng của bạn</h3>
            </div>
            <div class="container">
                <% @all_order.each do |item| %>
                <div class="row">
                    <div class="col-sm-2 anh">
                        <%= image_tag(item.hotel.image.url, alt: 'Image') %>
                    </div>
                    <div class="col-sm-3 tieude p-1">
                        <a href="<%= detail_path(:id => item.hotel.id)  %>">
                            <h5><%= item.hotel.name  %></h5>
                        </a>
                        <p>Tên: <%= item.name  %></p>
                        <p>Email: <%= item.email  %></p>
                        <p>Số điện thoại: <%= item.phone  %></p>

                    </div>
                    <div class="col-sm-3 tieude  p-1">

                        <p>Thời gian nhận phòng: <%= item.time  %></p>
                        <p>Loại phòng: <%= item.type_hotel  %></p>
                        <p>Ghi chú: <%= item.note  %></p>
                        <p>Thời gian đặt phòng: <%= item.updated_at.to_formatted_s(:db)  %></p>
                    </div>
                    <div class="col-sm-2 gia">
                        <h6>Giá: <%= number_to_currency(item.hotel.price_discount, unit: "đ",format: "%n %u", precision: 0)  %></h6>
                    </div>
                    <div class="col-sm-2 soluong">
                        <% if item.status==0 %>
                        <span class="badge badge-secondary btn-xoa p-2 mr-2">Đang chờ xử lý</span>
                        <a href="<%= order_cancel_path(:id=>item.id) %>" class="btn btn-sm btn-outline-danger" onclick='return confirm("Hủy đơn này!")'>
                            <i class="fas fa-window-close"></i>
                        </a>
                        <% elsif item.status==1 %>
                        <span class="badge badge-success btn-xoa p-2">Đã xác nhận</span>
                        <% else %>
                        <span class="badge badge-danger btn-xoa p-2">Đã hủy</span>
                        <% end %>
                    </div>
                </div>
                <% end %>

            </div>
        </div>

        <footer>
            <div class="tren">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 sec1">
                            <h3>Lang Co beach</h3>
                            <p>Mã số thuế: 031422xxx</p>
                            <p>Ngày cấp giấy phép: 01/01/2019</p>
                            <p>Ngày hoạt động: 01/01/2019</p>
                        </div>
                        <div class="col-lg-3 sec2">
                            <div class="tieude">
                                <h4>Liên Hệ</h4>
                            </div>
                            <div class="noidung">
                                <p><i class="fa fa-map-marker"></i><span> Trường đại học CNTT và TT Việt Hàn</span>
                                </p>
                                <p><i class="fa fa-phone"></i><span> 0336757208</span></p>
                                <p><i class="fa fa-envelope"></i><span> levantanald@gmail.com</span></p>
                                <p class="iconf">
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Facebook"> <i class="fab fa-facebook"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fab fa-instagram"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fab fa-twitter"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fab fa-pinterest"></i></a>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 sec3">
                            <div class="tieude">
                                <h4>Tin tức</h4>
                            </div>
                            <div class="noidung">
                                <ul>
                                    <li><a href="">Bản tin du lịch Việt</a></li>
                                    <li><a href="">Cẩm nang du lịch</a></li>
                                    <li><a href="">Tư vấn du lịch</a></li>
                                    <li><a href="">Tuyển dụng du lịch</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 sec4">
                            <div class="tieude">
                                <h4>Tour phổ biến</h4>
                            </div>
                            <div class="noidung">
                                <%= image_tag "img/footter.png" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="duoi">
                <p>© All rights reserved. Thiết kế website NT_4rever</p>
            </div>
        </footer>


        <!-- end main -->
    </div>

</div>
<span class="btn_top_a">
    <div class="btn_top" id="btn_top">
        <i class="fa fa-arrow-up"></i>
    </div>
</span>
<%= javascript_pack_tag 'index' %>
<%= javascript_pack_tag 'flickity' %>

app/views/articles/tintuc.html.erb
<div class="wrapper">

    <div class="main">
        <header>
            <nav class="nav_Bar container navbar navbar-expand-lg navbar-primary|secondary|success|danger|warning|info|light|dark bg-primary|secondary|success|danger|warning|info|light|dark">
                <a class="navbar-brand logo_tieude" href="<%= root_path %>">LangCoBeach</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="fas fa-bars icon_bar"></i>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<%= root_path %>">TRANG CHỦ <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= khachsan_path %>">KHÁCH SẠN</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<%= tintuc_path %>">TIN TỨC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= gioithieu_path %>">GIỚI THIỆU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= lienhe_path %>">LIÊN HỆ</a>
                        </li>
                        <li class="nav-item search_nav_cha">
                            <div class="search">
                                <div class="nav-link">
                                    <span>Tìm kiếm</span>
                                    <i class="fa fa-search"></i>
                                </div>
                            </div>
                            <div class="form_search_navbar flex-row">
                                <%= form_tag(search_path, method: :get) do   %>
                                <%= text_field_tag :text,"", class:'form-control', required: 'true' %>
                                <div class="icon_search_navbar">
                                    <button type="submit" class="form-control"><i class="fa fa-search"></i></button>
                                </div>
                                <% end %>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a href="<%= list_order_path %>">
                                <div class="giohang">
                                    <div class="nav-link">
                                        <span>Đơn hàng</span>
                                        <i class="fa fa-shopping-bag"></i>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="nav-item">
                            <% if session[:username] %>
                            <%= link_to 'logout', :action => 'go' do %>
                            <div class="giohang dangnhap">
                                <div class="nav-link">
                                    <span id="username"> <%= session[:username] %></span>
                                    <i class="fas fa-sign-out-alt"></i>
                                </div>
                            </div>
                            <% end %>
                            <% else %>
                            <%= link_to 'login', :action => 'go' do %>
                            <div class="giohang dangnhap">
                                <div class="nav-link">
                                    <span id="username"> Đăng nhập</span>
                                    <i class="fas fa-sign-in-alt"></i>
                                </div>
                            </div>
                            <% end %>
                            <% end %>
                        </li>
                    </ul>

                </div>
            </nav>
        </header>
        <!-- Ket thuc header -->
        <div class="main_tt">
            <div class="container">
                <div class="tieudetong">
                    <h4>TIN TỨC</h4>
                </div>
                <div class="row">
                    <div class="sidebar col-lg-3">
                        <div class="timkiem">
                            <%= form_tag(post_search_path, method: :get) do   %>
                            <%= text_field_tag :text,"", class:'form-control', required: 'true' %>
                            <button class="btn btn-success"><i class="fa fa-search"></i></button>
                            <% end %>
                        </div>
                        <div class="tieude">
                            <h5>BÀI VIẾT MỚI NHẤT</h5>
                        </div>
                        <div class="is-divider small"></div>
                        <% @all_post_latest.each do |item| %>
                        <div class="bvmoi">
                            <a href="<%= tintuc_chitiet_path(:id => item.id) %>">
                                <p><%= item.post_title%></p>
                            </a>
                        </div>
                        <% end%>

                    </div>
                    <% @all_post.each do |item| %>
                    <div class="sec1 col-lg-3">
                        <div class="date_time">
                            <p><%= item.created_at.to_formatted_s(:short) %></p>
                        </div>
                        <div class="nen">
                            <a href="<%= tintuc_chitiet_path(:id => item.id) %>">
                                <div class="noidung">
                                    <figure>
                                        <%= image_tag(item.post_image.url, alt: 'Image') if item.post_image? %>
                                    </figure>
                                    <figcaption>
                                        <div class="tieude">
                                            <h4><%= item.post_title %></h4>
                                        </div>
                                        <div class="is-divider small"></div>
                                        <div class="tomtat">
                                            <p><%= raw(item.post_desc) %>
                                            </p>
                                        </div>
                                    </figcaption>

                                </div>
                            </a>
                        </div>
                    </div>
                    <%end %>

                </div>
                <div class="row">
                    <div class="btn_load col-lg-12 text-center" style="display: flex;
    align-items: center;
    justify-content: center;">
                        <%== pagy_bootstrap_nav(@pagy) %>
                    </div>
                </div>
            </div>
        </div>

        <footer>
            <div class="tren">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 sec1">
                            <h3>Lang Co beach</h3>
                            <p>Mã số thuế: 031422xxx</p>
                            <p>Ngày cấp giấy phép: 01/01/2019</p>
                            <p>Ngày hoạt động: 01/01/2019</p>
                        </div>
                        <div class="col-lg-3 sec2">
                            <div class="tieude">
                                <h4>Liên Hệ</h4>
                            </div>
                            <div class="noidung">
                                <p><i class="fa fa-map-marker"></i><span> Trường đại học CNTT và TT Việt Hàn</span>
                                </p>
                                <p><i class="fa fa-phone"></i><span> 0336757208</span></p>
                                <p><i class="fa fa-envelope"></i><span> levantanald@gmail.com</span></p>
                                <p class="iconf">
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Facebook"> <i class="fab fa-facebook"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fab fa-instagram"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fab fa-twitter"></i></a>
                                    <a href="" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fab fa-pinterest"></i></a>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 sec3">
                            <div class="tieude">
                                <h4>Tin tức</h4>
                            </div>
                            <div class="noidung">
                                <ul>
                                    <li><a href="">Bản tin du lịch Việt</a></li>
                                    <li><a href="">Cẩm nang du lịch</a></li>
                                    <li><a href="">Tư vấn du lịch</a></li>
                                    <li><a href="">Tuyển dụng du lịch</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 sec4">
                            <div class="tieude">
                                <h4>Tour phổ biến</h4>
                            </div>
                            <div class="noidung">
                                <%= image_tag "img/footter.png" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="duoi">
                <p>© All rights reserved. Thiết kế website NT_4rever</p>
            </div>
        </footer>


        <!-- end main -->
    </div>

</div>
<span class="btn_top_a">
    <div class="btn_top" id="btn_top">
        <i class="fa fa-arrow-up"></i>
    </div>
</span>
<%= javascript_pack_tag 'index' %>
<%= javascript_pack_tag 'flickity' %>