config/routes.rb
Rails.application.routes.draw do
  # articles: controller index page
  root "articles#index"
  
  get "/articles", to: "articles#index"
  get "/khachsan", to: "articles#khachsan"
  get "/detail", to: "articles#detail"
  get "/tintuc", to: "articles#tintuc"
  get "/tintuc_chitiet", to: "articles#tintuc_chitiet"
  get "/gioithieu", to: "articles#gioithieu"
  get "/lienhe", to: "articles#lienhe"
  get "search", to: "articles#search"
  get "post_search", to: "articles#post_search"
  post "new_order", to: "order#create"
  get "list_order", to: "articles#list_order"

  resources :comments

  # users, session: controller login, register and logout
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  get  "logout"   => "session#destroy"
  get "register"    => "users#new"
  resources :users

  # admin space
  get "admin", to: "admin_session#new"
  post "admin_login", to: "admin_session#login"
  get "admin_logout", to: "admin_session#destroy"
  get "dashboard", to: "admin#index"

  scope 'admin' do
      get 'category', to: 'category#category'
      get 'new_category', to: 'category#new'
      post 'create_category', to: 'category#create'
      get 'delete_category', to: 'category#destroy'
      get 'edit_category', to: 'category#edit'
      post 'update_category', to: 'category#update'

      get 'product', to: 'product#product'
      get 'new_product', to: 'product#new'
      post 'create_product', to: 'product#create'
      get 'delete_product', to: 'product#destroy'
      get 'edit_product', to: 'product#edit'
      post 'update_product', to: 'product#update'

      get 'gallery', to: 'gallery#show'
      get 'new_gallery', to: 'gallery#new'
      post 'create_gallery', to: 'gallery#create'

      get 'post', to: 'post#post'
      get 'new_post', to: 'post#new'
      post 'create_post', to: 'post#create'
      get 'edit_post', to: 'post#edit'
      post 'update_post', to: 'post#update'
      get 'delete_post', to: 'post#destroy'

      get 'all_comments', to: 'comments#index'
      get 'delete_comment', to: 'comments#destroy'

      get 'all_order', to: 'order#index'
      get 'order_confirm', to: 'order#confirm'
      get 'order_cancel', to: 'order#cancel'

      get 'account', to: 'admin#account'
      get 'change_pass' , to: "admin#change_pass"
      post 'update_account', to: "admin#update"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_hotel.rb
class CategoryHotel < ApplicationRecord
    has_many :hotel, :dependent => :destroy
    has_rich_text :category_desc
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/gallery_hotel.rb
class GalleryHotel < ApplicationRecord
  belongs_to :hotel
  mount_uploaders :path, ImageUploader
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category_hotel
  has_one :gallery_hotel, :dependent => :delete
  has_many :comment, :dependent => :destroy
  has_rich_text :desc 
  has_rich_text :content

  validate :check_price 

  def check_price
    if price_discount? && price_discount.to_i > price.to_i 
      errors.add(:price, "Price error!")
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :hotel
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :post_desc
    has_rich_text :post_content
    mount_uploader :post_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, uniqueness: { case_sensitive: false }
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    layout 'admin_layout'

    def post
        check_session
        @tintuc_active = 'active'
        @pagy, @all_post = pagy(Post.all.order("id DESC"), items: 10)
    end
 
    def new
        check_session
        @tintuc_active = 'active'
    end

    def create
        check_session
        @post = Post.new post_params
        if @post.save 
            flash[:success] = "Thêm bài viết thành công!"
            redirect_to :controller => 'post', :action => 'post'
        else  
            flash[:success] = "Thêm bài viết thất bại!"
            render :new
        end
    end

    def  edit 
        check_session
        @tintuc_active = 'active'
        @post = Post.find(params[:id])
    end

    def update
        check_session
        @post = Post.find(params[:id])
        if @post.update(post_params)
          flash[:success] = "Sửa bài viết thành công!"
          redirect_to :controller => 'post', :action => 'post'
        else
          flash[:danger] = "Sửa bài viết thất bại!"
          redirect_to :controller => 'post', :action => 'post'
        end
    end

    def destroy 
        check_session
        @post = Post.find(params[:id])
        if @post.destroy 
            flash[:success] = "Xóa bài viết thành công!"
            redirect_to :controller => 'post', :action => 'post'
        else
            flash[:danger] = "Xóa bài viết thất bại!"
            redirect_to :controller => 'post', :action => 'post'
         end
    end

    # hàm lấy dữ liệu từ form
    private
    def post_params
      params.require(:post).permit :post_title, :post_desc, :post_content, :post_meta, :post_image
    end

    private
    def check_session 
      if !session[:admin] 
        redirect_to admin_path
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/account.html.erb
 <h1 class="m-0 text-dark pb-2">Tài khoản</h1>

 <div class="card-body">
     <% flash.each do |key, value| %>
     <div class="callout callout-<%= key %>">
         <p><%= value %></p>
     </div>
     <% end %>
 </div>
 <div class="row">
     <div class="col-12">
         <div class="card">
             <div class="card-header">
                 <a href="<%= login_path %>" target="_blank" class="btn btn-outline-info">Thêm tài khoản</a>

                 <div class="card-tools">
                     <div class="input-group input-group-sm" style="width: 150px;">
                         <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                         <div class="input-group-append">
                             <button type="submit" class="btn btn-default">
                                 <i class="fas fa-search"></i>
                             </button>
                         </div>
                     </div>
                 </div>
             </div>
             <!-- /.card-header -->
             <div class="card-body table-responsive p-0" style="height: 400px;">
                 <table class="table table-head-fixed text-nowrap">
                     <thead>
                         <tr>
                             <th>id</th>
                             <th>name</th>
                             <th>email</th>
                             <th>role</th>
                             <th>updated_at</th>
                             <th>edit</th>
                         </tr>
                     </thead>
                     <tbody>
                         <% if @all_account %>
                         <% @all_account.each do |acc| %>
                         <tr>
                             <td>
                                 <%= acc.id  %>
                             </td>
                             <td>
                                 <%= acc.firstName  %> <%= acc.lastName  %>
                             </td>
                             <td>
                                 <%= acc.email  %>
                             </td>
                             <td>
                                 <%= acc.role  %>
                             </td>
                             <td>
                                 <%= acc.updated_at %>
                             </td>
                              <td>
                                 <a href="<%= change_pass_path(:id =>acc.id) %>" class="btn btn-sm btn-outline-primary" onclick='return confirm("Thay đổi thông tin tài khoản này!");'>
                                     <i class="far fa-edit"></i>
                                 </a>
                             </td>
                         </tr>
                         <% end %>
                         <% end %>
                     </tbody>
                 </table>

             </div>
             <div class="ml-2">
                 <%== pagy_bootstrap_nav(@pagy) %>
             </div>

             <!-- /.card-body -->
         </div>
         <!-- /.card -->
     </div>
 </div>

app/views/admin/change_pass.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Sửa thông tin tài khoản: <%= @account.lastName%></h3>
            </div>
            <section class="content" style="min-height: auto;display: flex;justify-content: center;">
                <% flash.each do |key, value| %>
                <div class="row">
                    <div class="alert alert-<%= key %>">
                        <%= value %>
                    </div>
                </div>
                <% end %>
            </section>

            <%= form_for:account,url: update_account_path(:id => @account.id) do |f| %>
            <div class="card-body">
                <div class="form-group">
                    <label for="category_name">Họ, tên đệm </label>
                    <%=f.text_field :firstName, class:'form-control', required: 'true' %>
                </div>
                <div class="form-group">
                    <label for="category_name">Tên </label>
                    <%=f.text_field :lastName, class:'form-control', required: 'true' %>
                </div>
                <div class="form-group">
                    <label for="category_name">Role </label>
                     <%= f.select(:role, ["customer", "admin"], {}, { :class => 'form-control' }) %>
                </div>
                <p class="text-danger">Nếu không thay đổi mật khẩu, vui lòng bỏ qua 2 trường này! </p>
                <div class="form-group">
                    <label for="category_name">Mật khẩu </label>
                    <%= f.password_field :password, class: "form-control", placeholder: "Mật khẩu" %>
                </div>
                <div class="form-group">
                    <label for="category_name">Nhập lại mật khẩu </label>
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Nhập lại mật khẩu"%>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <%= f.submit "Submit", class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/base/_control_sidebar.html.erb
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

app/views/base/_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

app/views/base/_header.html.erb
 <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <%= image_tag "admin/img/user1-128x128.jpg",class:'img-size-50 mr-3 img-circle' %>
  
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
            <%= image_tag "admin/img/user8-128x128.jpg", class:'img-size-50 img-circle mr-3' %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
            <%= image_tag "admin/img/user3-128x128.jpg", class:'img-size-50 img-circle mr-3' %>
           
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

app/views/base/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <%= image_tag "admin/img/AdminLTELogo.png", class:'brand-image img-circle elevation-3', style:"opacity: .8" %>
        <span class="brand-text font-weight-light">Dashboard</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <%= image_tag "admin/img/user2-160x160.jpg", class: 'img-circle elevation-2' %>
            </div>
            <div class="info">
                <a href="#" class="d-block"><%= session[:admin]%></a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Quản lý sản phẩm
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="<%= category_path %>" class="nav-link <%= @danhmuc_active%>">
                                <i class="fas fa-bars nav-icon"></i>
                                <p>Danh mục</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<%= product_path %>" class="nav-link <%= @sanpham_active%>">
                                <i class="fas fa-hotel nav-icon"></i>
                                <p>Sản phẩm</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<%= all_order_path %>" class="nav-link <%= @donhang_active%>">
                                <i class="fas fa-shopping-cart  nav-icon"></i>
                                <p>Đơn hàng</p>
                            </a>
                        </li>
                    </ul>
                </li>



                <li class="nav-item  menu-open">
                    <a href="#" class="nav-link">
                      <i class="fas fa-archive nav-icon"></i>
                        <p>
                            Khác
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="<%= all_comments_path %>" class="nav-link <%= @binhluan_active%>">
                                <i class="fas fa-comments nav-icon"></i>
                                <p>
                                    Bình luận
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<%= post_path %>" class="nav-link <%= @tintuc_active%>">
                                <i class="fas fa-newspaper nav-icon"></i>
                                <p>
                                    Tin tức
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<%= account_path %>" class="nav-link <%= @taikhoan_active%>">
                              <i class="fas fa-user-circle nav-icon"></i>
                                <p>Tài khoản</p>
                            </a>
                        </li>
                    </ul>

                </li>



                <li class="nav-item">
                    <a href="<%= admin_logout_path %>" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i>
                        <p>
                            Đăng xuất
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

app/views/shared/_pagination.html.erb

<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
<%#                            -%>  <ul class="pagination">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>