config/routes.rb
Rails.application.routes.draw do
  # articles: controller index page
  root "articles#index"
  
  get "/articles", to: "articles#index"
  get "/khachsan", to: "articles#khachsan"
  get "/detail", to: "articles#detail"
  get "/tintuc", to: "articles#tintuc"
  get "/tintuc_chitiet", to: "articles#tintuc_chitiet"
  get "/gioithieu", to: "articles#gioithieu"
  get "/lienhe", to: "articles#lienhe"
  get "search", to: "articles#search"
  get "post_search", to: "articles#post_search"
  post "new_order", to: "order#create"
  get "list_order", to: "articles#list_order"

  resources :comments

  # users, session: controller login, register and logout
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  get  "logout"   => "session#destroy"
  get "register"    => "users#new"
  resources :users

  # admin space
  get "admin", to: "admin_session#new"
  post "admin_login", to: "admin_session#login"
  get "admin_logout", to: "admin_session#destroy"
  get "dashboard", to: "admin#index"

  scope 'admin' do
      get 'category', to: 'category#category'
      get 'new_category', to: 'category#new'
      post 'create_category', to: 'category#create'
      get 'delete_category', to: 'category#destroy'
      get 'edit_category', to: 'category#edit'
      post 'update_category', to: 'category#update'

      get 'product', to: 'product#product'
      get 'new_product', to: 'product#new'
      post 'create_product', to: 'product#create'
      get 'delete_product', to: 'product#destroy'
      get 'edit_product', to: 'product#edit'
      post 'update_product', to: 'product#update'

      get 'gallery', to: 'gallery#show'
      get 'new_gallery', to: 'gallery#new'
      post 'create_gallery', to: 'gallery#create'

      get 'post', to: 'post#post'
      get 'new_post', to: 'post#new'
      post 'create_post', to: 'post#create'
      get 'edit_post', to: 'post#edit'
      post 'update_post', to: 'post#update'
      get 'delete_post', to: 'post#destroy'

      get 'all_comments', to: 'comments#index'
      get 'delete_comment', to: 'comments#destroy'

      get 'all_order', to: 'order#index'
      get 'order_confirm', to: 'order#confirm'
      get 'order_cancel', to: 'order#cancel'

      get 'account', to: 'admin#account'
      get 'change_pass' , to: "admin#change_pass"
      post 'update_account', to: "admin#update"
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :hotel
    belongs_to :user
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    layout "admin_layout"
    def index
        check_session 
        @donhang_active = 'active'
        @pagy, @all_order = pagy(Order.all.order("id DESC"), items: 10)
    end

    def create
        @order = Order.new order_params
        @order.status = 0
        if @order.save 
            redirect_to list_order_path
        else  
            
        end
    end

    def confirm
        check_session 
        @order = Order.find(params[:id])
        UserMailer.confirm_email(@order).deliver_later
        @order.status = 1
        if @order.save 
            flash[:success] = "Xác nhận thành công!"
            redirect_back(fallback_location: root_path)
        else  
            
        end
    end

    def cancel
        @order = Order.find(params[:id])
        @order.status = 2
        if @order.save 
            flash[:success] = "Hủy nhận thành công!"
            redirect_back(fallback_location: root_path)
        else  
            
        end
    end

     # hàm lấy dữ liệu từ form
     private
     def order_params
       params.require(:order).permit :name, :email, :phone, :note, :user_id, :hotel_id, :time, :type_hotel
     end

     private
    def check_session 
      if !session[:admin] 
        redirect_to admin_path
      end
    end

end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
 <h1 class="m-0 text-dark pb-2">Đơn hàng</h1>

 <div class="card-body">
     <% flash.each do |key, value| %>
     <div class="callout callout-<%= key %>">
         <p><%= value %></p>
     </div>
     <% end %>
 </div>
 <div class="row">
     <div class="col-12">
         <div class="card">
             <div class="card-header">
            

                 <div class="card-tools">
                     <div class="input-group input-group-sm" style="width: 150px;">
                         <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                         <div class="input-group-append">
                             <button type="submit" class="btn btn-default">
                                 <i class="fas fa-search"></i>
                             </button>
                         </div>
                     </div>
                 </div>
             </div>
             <!-- /.card-header -->
             <div class="card-body table-responsive p-0" style="height: 400px;">
                 <table class="table table-head-fixed text-nowrap">
                     <thead>
                         <tr>
                             <th>id</th>
                             <th>Trạng thái</th>
                             <th>Tên khách hàng</th>
                             <th>Số điện thoại</th>
                             <th>Email</th>
                             <th>Khách sạn</th>
                             <th>Loại phòng</th>
                             <th>Thời gian đặt phòng</th>
                             <th>Thời gian nhận phòng</th>
                             <th>Ghi chú</th>
                             <th>user_id</th>
                            <th>Chỉnh sửa</th>
                         </tr>
                     </thead>
                     <tbody>
                         <% if @all_order %>
                         <% @all_order.each do |item| %>
                         <tr>
                             <td>
                                 <%= item.id  %>
                             </td>
                             <td>
                                <% if item.status==0 %>
                                   <span class="badge badge-secondary">Đang chờ xử lý</span>
                                <% elsif item.status==1 %>
                                  <span class="badge badge-success">Đã xác nhận</span>
                                <% else %>
                                   <span class="badge badge-danger">Đã hủy</span>
                                <% end %>
                             </td>
                             <td>
                                 <%= item.name  %>
                             </td>
                            <td>
                                 <%= item.phone  %>
                             </td>
                             <td>
                                 <%= item.email  %>
                             </td>
                             <td>
                                <a href="<%= detail_path(:id => item.hotel_id) %>" target="_blank">
                                 <%= item.hotel.name %>
                                 </a>
                             </td>
                             <td>
                                 <%= item.type_hotel %>
                             </td>
                             <td>
                                 <%= item.created_at.to_formatted_s(:db) %>
                             </td>
                             <td>
                                 <%= item.time %>
                             </td>
                             <td>
                                 <%= item.note  %>
                             </td>
                             <td>
                                 <%= item.user_id  %>
                             </td>
                             <td> 
                              <a href="<%= order_confirm_path(:id=>item.id) %>" class="btn btn-sm btn-outline-success">
                                     <i class="fas fa-check"></i>
                                </a>
                                <a href="<%= order_cancel_path(:id=>item.id) %>" class="btn btn-sm btn-outline-danger">
                                     <i class="fas fa-window-close"></i>
                                 </a>
                             </td>
                         </tr>
                         <% end %>
                         <% end %>
                     </tbody>
                 </table>

             </div>
             <div class="ml-2">
                    <%== pagy_bootstrap_nav(@pagy) %>
             </div>

             <!-- /.card-body -->
         </div>
         <!-- /.card -->
     </div>
 </div>