config/routes.rb
Rails.application.routes.draw do
  # articles: controller index page
  root "articles#index"
  
  get "/articles", to: "articles#index"
  get "/khachsan", to: "articles#khachsan"
  get "/detail", to: "articles#detail"
  get "/tintuc", to: "articles#tintuc"
  get "/tintuc_chitiet", to: "articles#tintuc_chitiet"
  get "/gioithieu", to: "articles#gioithieu"
  get "/lienhe", to: "articles#lienhe"
  get "search", to: "articles#search"
  get "post_search", to: "articles#post_search"
  post "new_order", to: "order#create"
  get "list_order", to: "articles#list_order"

  resources :comments

  # users, session: controller login, register and logout
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  get  "logout"   => "session#destroy"
  get "register"    => "users#new"
  resources :users

  # admin space
  get "admin", to: "admin_session#new"
  post "admin_login", to: "admin_session#login"
  get "admin_logout", to: "admin_session#destroy"
  get "dashboard", to: "admin#index"

  scope 'admin' do
      get 'category', to: 'category#category'
      get 'new_category', to: 'category#new'
      post 'create_category', to: 'category#create'
      get 'delete_category', to: 'category#destroy'
      get 'edit_category', to: 'category#edit'
      post 'update_category', to: 'category#update'

      get 'product', to: 'product#product'
      get 'new_product', to: 'product#new'
      post 'create_product', to: 'product#create'
      get 'delete_product', to: 'product#destroy'
      get 'edit_product', to: 'product#edit'
      post 'update_product', to: 'product#update'

      get 'gallery', to: 'gallery#show'
      get 'new_gallery', to: 'gallery#new'
      post 'create_gallery', to: 'gallery#create'

      get 'post', to: 'post#post'
      get 'new_post', to: 'post#new'
      post 'create_post', to: 'post#create'
      get 'edit_post', to: 'post#edit'
      post 'update_post', to: 'post#update'
      get 'delete_post', to: 'post#destroy'

      get 'all_comments', to: 'comments#index'
      get 'delete_comment', to: 'comments#destroy'

      get 'all_order', to: 'order#index'
      get 'order_confirm', to: 'order#confirm'
      get 'order_cancel', to: 'order#cancel'

      get 'account', to: 'admin#account'
      get 'change_pass' , to: "admin#change_pass"
      post 'update_account', to: "admin#update"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_hotel.rb
class CategoryHotel < ApplicationRecord
    has_many :hotel, :dependent => :destroy
    has_rich_text :category_desc
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/gallery_hotel.rb
class GalleryHotel < ApplicationRecord
  belongs_to :hotel
  mount_uploaders :path, ImageUploader
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category_hotel
  has_one :gallery_hotel, :dependent => :delete
  has_many :comment, :dependent => :destroy
  has_rich_text :desc 
  has_rich_text :content

  validate :check_price 

  def check_price
    if price_discount? && price_discount.to_i > price.to_i 
      errors.add(:price, "Price error!")
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :hotel
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :post_desc
    has_rich_text :post_content
    mount_uploader :post_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, uniqueness: { case_sensitive: false }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin_layout"
  def index
    if !session[:admin] 
      redirect_to admin_path
    end
  end

  def account
    check_session
    @taikhoan_active = 'active'
    @pagy, @all_account = pagy(User.all.order("id DESC"), item: 10)
  end

  def change_pass
    check_session
    @taikhoan_active = 'active'
    @account = User.find(params[:id])
  end
  
  def update 
    check_session
    @account = User.find(params[:id])
    if @account.update(account_params)
      flash[:success] = "Sửa tài khoản thành công!"
      redirect_to account_path
    else
      flash[:danger] = "Sửa tài khoản thất bại!"
      redirect_to account_path
    end
  end
  

  private
  def check_session 
    if !session[:admin] 
      redirect_to admin_path
    end
  end

  # hàm lấy dữ liệu từ form
  private
  def account_params
    params.require(:account).permit :firstName, :lastName, :role, :password, :password_confirmation
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
    layout "admin_layout"
    def show
        check_session
        @sanpham_active = 'active'
        @gallery = GalleryHotel.where("hotel_id = :id",{id: params[:id]})
    end

    def new
        check_session
        @sanpham_active = 'active'
        @gallery = GalleryHotel.new
        
    end

    def create 
        check_session
        u = GalleryHotel.where("hotel_id = :id",{id: params[:id]}).first()
        if u 
            u.update(gallery_params)
            flash[:success] = "Thêm ảnh sản phẩm thành công!"
            redirect_to gallery_path(:id=>params[:id])
        else 
            u = GalleryHotel.create gallery_params
            if u.save
                flash[:success] = "Thêm ảnh sản phẩm thành công!"
                redirect_to gallery_path(:id=>params[:id])
            else
                flash[:danger] = "Thêm ảnh sản phẩm thất bại!"
                render :new
            end
        end
        
    end
    
    def gallery_params
        params.require(:gallery).permit({path: []},:hotel_id)
    end

    private
    def check_session 
      if !session[:admin] 
        redirect_to admin_path
      end
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
    layout 'admin_layout'

    def post
        check_session
        @tintuc_active = 'active'
        @pagy, @all_post = pagy(Post.all.order("id DESC"), items: 10)
    end
 
    def new
        check_session
        @tintuc_active = 'active'
    end

    def create
        check_session
        @post = Post.new post_params
        if @post.save 
            flash[:success] = "Thêm bài viết thành công!"
            redirect_to :controller => 'post', :action => 'post'
        else  
            flash[:success] = "Thêm bài viết thất bại!"
            render :new
        end
    end

    def  edit 
        check_session
        @tintuc_active = 'active'
        @post = Post.find(params[:id])
    end

    def update
        check_session
        @post = Post.find(params[:id])
        if @post.update(post_params)
          flash[:success] = "Sửa bài viết thành công!"
          redirect_to :controller => 'post', :action => 'post'
        else
          flash[:danger] = "Sửa bài viết thất bại!"
          redirect_to :controller => 'post', :action => 'post'
        end
    end

    def destroy 
        check_session
        @post = Post.find(params[:id])
        if @post.destroy 
            flash[:success] = "Xóa bài viết thành công!"
            redirect_to :controller => 'post', :action => 'post'
        else
            flash[:danger] = "Xóa bài viết thất bại!"
            redirect_to :controller => 'post', :action => 'post'
         end
    end

    # hàm lấy dữ liệu từ form
    private
    def post_params
      params.require(:post).permit :post_title, :post_desc, :post_content, :post_meta, :post_image
    end

    private
    def check_session 
      if !session[:admin] 
        redirect_to admin_path
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gallery/new.html.erb
<div class="row">
    <!-- left column -->
    <div class="col-md-8">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Thêm ảnh sản phẩm</h3>
            </div>
            <section class="content" style="min-height: auto;display: flex;justify-content: center;">
                <% flash.each do |key, value| %>
                <div class="row">
                    <div class="alert alert-<%= key %>">
                        <%= value %>
                    </div>
                </div>
                <% end %>
            </section>
            <!-- /.card-header -->
            <!-- form start -->
            <%= form_for:gallery ,url: create_gallery_path(:id=>params[:id]) do |f| %>
            <div class="card-body">
                <div class="form-group">
                    <label for="image">Ảnh</label>
                    <%= f.file_field :path, multiple: true, class: 'form-control', required: 'true' %>
                    <%= f.hidden_field :hotel_id, value: params[:id] %>
                </div>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <%= f.submit "Submit", class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
        <!-- /.card -->


    </div>
    <!-- /.card -->
</div>
<!--/.col (right) -->
</div>

app/views/gallery/show.html.erb
 <h1 class="m-0 text-dark pb-2">Thư viện ảnh sản phẩm</h1>

 <div class="card-body">
     <% flash.each do |key, value| %>
     <div class="callout callout-<%= key %>">
         <p><%= value %></p>
     </div>
     <% end %>
 </div>
 <div class="row">
     <div class="col-12">
         <div class="card">
             <div class="card-header">
                 <a href="<%= new_gallery_path(:id => params[:id]) %>" class="btn btn-outline-info">Thêm ảnh sản phẩm</a>
                 <div class="card-tools">
                     <div class="input-group input-group-sm" style="width: 150px;">
                         <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                         <div class="input-group-append">
                             <button type="submit" class="btn btn-default">
                                 <i class="fas fa-search"></i>
                             </button>
                         </div>
                     </div>
                 </div>
             </div>
             <!-- /.card-header -->
             <div class="card-body table-responsive p-0" style="height: 400px;">
                 <table class="table table-head-fixed text-nowrap">
                     <thead>
                         <tr>
                             <th>img</th>
                             <th>edit</th>
                         </tr>
                     </thead>
                     <tbody>
                         <% if @gallery %>
                         <% @gallery.each do |item| %>
                         
                                 <% item.path.each do |p| %>
                                 <tr>
                             <td>
                                 <%= image_tag(p.url,style: "width:300px;", alt: 'Image') %>
                                  </td>
                                 <% end %>
                            
                         </tr>
                         <% end %>
                         <% end %>

                     </tbody>
                 </table>
             </div>

             <!-- /.card-body -->
         </div>
         <!-- /.card -->
     </div>
 </div>